services:

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    ports:
      - "80:80"
      - "443:443"
      - "3128:3128"
    expose:
      - 80 # http
      - 443 # https
      - 3128 # proxy
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/nas/DockerServices}/caddy/CaddyFile:/etc/caddy/Caddyfile
      - ${DOCKER_VOLUME_STORAGE:-/mnt/nas/DockerServices}/caddy/data:/data
      - ${DOCKER_VOLUME_STORAGE:-/mnt/nas/DockerServices}/caddy/config:/config