version: "3.9"

services:

  ui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-ui
    restart: always
    ports:
      - 7000:8080 # Web UI
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/nas/DockerServices}/ollama/open-webui:/app/backend/data
    environment:
      # - "ENABLE_SIGNUP=false"
      - "OLLAMA_BASE_URL=http://ollama:11434"
      # - CHROMA_HTTP_HOST=chromadb
      # - CHROMA_HTTP_PORT=8000
      # - CHROMA_TENANT=default_tenant
      # - VECTOR_DB=chroma
      - RAG_EMBEDDING_ENGINE=ollama
      - RAG_EMBEDDING_MODEL=nomic-embed-text-v1.5
      - RAG_EMBEDDING_MODEL_TRUST_REMOTE_CODE=true
    networks:
      - ai-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - 11434:11434 # Web UI
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/nas/DockerServices}/ollama/data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    networks:
      - ai-network

networks:
  ai-network:
    external: true
