# This Services is currently running on Truenas SCALE in order to have direct access to the NAS storage.
# Problems Observed:
# - Mounting leads to Calibre locking database.
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined # Required for GUI apps
    environment:
      - PUID=3005 # optional
      - PGID=3000 # optional
      - TZ=Europe/Prague
      # - PASSWORD=yourpassword  # Optional - set a password for Calibre GUI
    volumes:
      - /mnt/nas/Media/Books:/config
    ports:
      - "8182:8080"  # Calibre GUI
      - "8183:8181"  # Optional: HTTPS for GUI
    restart: unless-stopped
    networks:
      - media-network

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    depends_on:
      - calibre
    environment:
      - PUID=3005 # optional
      - PGID=3000 # optional
      - TZ=Europe/Prague
      # - DOCKER_MODS=linuxserver/mods:universal-calibre  # Enables full Calibre features
    volumes:
      - /mnt/nas/DockerServices/calibre:/config
      - /mnt/nas/Media/Books:/books:z
    ports:
      - "8184:8083"  # Web UI for browsing books
    restart: unless-stopped
    networks:
      - media-network
    

networks:
  media-network:
    external: true